// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrmq68W9yaNqenFUvyzGlnpuT0XbWc0co',
    appId: '1:906117552795:web:ae385346000cd777b2c43e',
    messagingSenderId: '906117552795',
    projectId: 'chat-app-14184',
    authDomain: 'chat-app-14184.firebaseapp.com',
    storageBucket: 'chat-app-14184.appspot.com',
    measurementId: 'G-ZK07WXZC4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk7Og0cAYnZjh2Zi0RpeiUA1C5NqJYydA',
    appId: '1:906117552795:android:ab98c8053f90b0fcb2c43e',
    messagingSenderId: '906117552795',
    projectId: 'chat-app-14184',
    storageBucket: 'chat-app-14184.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbydB-V7ReJWA_qLstRniGxCrHgZfXzk',
    appId: '1:906117552795:ios:0e731b9d8b364871b2c43e',
    messagingSenderId: '906117552795',
    projectId: 'chat-app-14184',
    storageBucket: 'chat-app-14184.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXbydB-V7ReJWA_qLstRniGxCrHgZfXzk',
    appId: '1:906117552795:ios:64418acdb56a270bb2c43e',
    messagingSenderId: '906117552795',
    projectId: 'chat-app-14184',
    storageBucket: 'chat-app-14184.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
